# -*- coding: utf-8 -*-
"""final coding uts terabytes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luVdmg8wxto6C2E6hGdeCJYXIgcVuiNx

# **TERABYTES**

**1. Sonya Audina Akbar (24083010013)**

**2. Fanny Widya Cahyani (24083010045)**

**3. Siti Naia Hesti Rachmawati (24083010047)**

**4. M. Wildan Sultansyah (240830100**

# **Deskripsi Data**

**Metode Pengambilan Data**

> Data diperoleh melalui teknik Web Scraping secara mandiri pada platform Lazada Indonesia. Proses pengambilan data berfokus pada toko resmi (official store) Watsons dan Dan+Dan untuk memastikan validitas sumber.

**Spesifikasi Data**

**1. Toko Watsons**

> Sumber: Lazada Indonesia

> Waktu Pengambilan: 2 April 2026

> Jumlah Data: 2000 baris dan 14 kolom

> Atribut Data: toko, nama_produk, harga, harga_original, diskon, rating, jumlah_review, jumlah_terjual, nama_toko_lazada, lokasi, brand, url_produk, url_gambar, tanggal_scraping


**2. Toko Dan+Dan**

> Sumber: Lazada Indonesia

> Waktu Pengambilan: 7 April 2026

> Jumlah Data: 1.666 baris

> Atribut Data: toko, nama_produk, harga, harga_origin, diskon, rating, jumlah_review, jumlah_terjual, lokasi, kategori, brand, url_produk, url_gambar, tanggal_scraping


**3. Dataset FInal yang Sudah Di Merge**

> Sumber: Lazada Indonesia

> Jumlah Data: 3.666 baris

> Atribut Data: toko, nama_produk, harga, harga_original, diskon, rating, jumlah_review, jumlah_terjual, lokasi, url_produk, url_gambar, tanggal_scraping

# **Load Data**
"""

# load data
import pandas as pd
import re
import matplotlib.pyplot as plt

url_watsons = "https://raw.githubusercontent.com/naiarch/UTS-Big-Data-Web-Scraping-Lazada/main/lazada_watsons.csv"
url_dandan = "https://raw.githubusercontent.com/naiarch/UTS-Big-Data-Web-Scraping-Lazada/main/lazada_dandan.csv"

df_watsons = pd.read_csv(url_watsons, sep=";", encoding="latin-1", engine="python")
df_dandan = pd.read_csv(url_dandan, sep=",", encoding="latin-1", engine="python")

"""# **Toko Watsons**"""

df_watsons.head()

df_watsons.tail()

df_watsons.info()

# @title rename kolom toko
df_watsons.rename(columns={'ï»¿toko': 'toko'}, inplace=True)
df_watsons.head()

# @title drop kolom brand
df_watsons.drop(columns=['brand'], inplace=True)
df_watsons.info()

# @title cleaning kolom diskon
df_watsons['diskon'] = df_watsons['diskon'].str.extract(r'(\d+)')
df_watsons['diskon'] = pd.to_numeric(df_watsons['diskon'], errors='coerce') / 100

df_watsons.head()

df_watsons.info()

# @title cleaning kolom rating

df_watsons['rating'] = df_watsons['rating'].str.replace(',', '.', regex=False)
df_watsons['rating'] = pd.to_numeric(df_watsons['rating'], errors='coerce')

# membulatkan 1 angka belakang
df_watsons['rating'] = df_watsons['rating'].round(1)

df_watsons.head()

df_watsons.info()

# @title mengubah tipe data kolom harga_original
df_watsons['harga_original'] = df_watsons['harga_original'].astype('Int64')
df_watsons.info()

# @title drop kolom nama_toko_lazada
df_watsons.drop(columns=['nama_toko_lazada'], inplace=True)
df_watsons.info()

df_watsons.describe()

# @title cek produk yang harganya mahal buanget
df_watsons.loc[
    df_watsons['harga'] == df_watsons['harga'].max(),
    ['nama_produk', 'harga', 'harga_original', 'diskon', 'jumlah_terjual']
]

# @title cek produk yang harga_originalnya muahal juga
df_watsons.loc[
    df_watsons['harga_original'] == df_watsons['harga_original'].max(),
    ['nama_produk', 'harga', 'harga_original', 'diskon', 'jumlah_terjual']
]

"""# **Toko DanDan**"""

df_dandan.head()

df_dandan.tail()

df_dandan.info()

# @title rename kolom toko
df_dandan.rename(columns={'ï»¿toko': 'toko'}, inplace=True)
df_dandan.head()

# @title rename kolom harga_origin
df_dandan.rename(columns={'harga_origin': 'harga_original'}, inplace=True)
df_dandan.head()

# @title drop kolom kategori dan brand
df_dandan.drop(columns=['kategori', 'brand'], inplace=True)
df_dandan.info()

# @title cleaning kolom diskon
df_dandan['diskon'] = df_dandan['diskon'].str.extract(r'(\d+)')
df_dandan['diskon'] = pd.to_numeric(df_dandan['diskon'], errors='coerce') / 100

df_dandan.head()

df_dandan.info()

# @title cleaning kolom harga, harga_original, jumlah_review, dan jumlah_terjual

# kolom harga
df_dandan['harga'] = (
    df_dandan['harga']
    .str.replace('Rp', '', regex=False)
    .str.replace('.', '', regex=False)
)
df_dandan['harga'] = pd.to_numeric(df_dandan['harga'], errors='coerce')

# kolom harga_original
df_dandan['harga_original'] = (
    df_dandan['harga_original']
    .str.replace('Rp', '', regex=False)
    .str.replace('.', '', regex=False)
)
df_dandan['harga_original'] = pd.to_numeric(df_dandan['harga_original'], errors='coerce')

# kolom jumlah_review
df_dandan['jumlah_review'] = df_dandan['jumlah_review'].astype('Int64')

# kolom jumlah_terjual
df_dandan['jumlah_terjual'] = pd.to_numeric(df_dandan['jumlah_terjual'], errors='coerce')
df_dandan['jumlah_terjual'] = df_dandan['jumlah_terjual'].astype('Int64')

df_dandan[['harga', 'harga_original', 'jumlah_review', 'jumlah_terjual']].head(10)

df_dandan.info()

# @title cleaning lanjutan kolom harga dan harga_original
df_dandan['harga'] = df_dandan['harga'].astype('Int64')
df_dandan['harga_original'] = df_dandan['harga_original'].astype('Int64')

df_dandan.head()

df_dandan.info()

df_dandan.describe()

# @title cek produk yang harganya mahal buanget
df_dandan.loc[
    df_dandan['harga'] == df_dandan['harga'].max(),
    ['nama_produk', 'harga', 'harga_original', 'diskon', 'jumlah_terjual']
]

# @title cek produk_original yang harganya mahal buanget
df_dandan.loc[
    df_dandan['harga_original'] == df_dandan['harga_original'].max(),
    ['nama_produk', 'harga', 'harga_original', 'diskon', 'jumlah_terjual']
]

"""# **Merge Dataset**"""

# @title menyamakan tipe data int64 ke Int64
cols_int = ['harga', 'harga_original', 'jumlah_review', 'jumlah_terjual']

for col in cols_int:
    df_watsons[col] = df_watsons[col].astype('Int64')
    df_dandan[col] = df_dandan[col].astype('Int64')

df_watsons.info()

df_dandan.info()

# @title merge data (stacking)
df = pd.concat([df_watsons, df_dandan], ignore_index=True)
df.head()

df.tail()

"""# **Data Understanding**"""

df.info()

# @title statistik deskriptif
df.describe()

# @title cek missing value
df.isnull().sum()

"""# **Data Cleaning**"""

# @title drop kolom nama_produk dan harga yang missing
df = df.dropna(subset=['nama_produk', 'harga'])
df.info()

# @title handle kolom diskon, jumlah_review, dan jumlah_terjual
df['diskon'] = df['diskon'].fillna(0)
df['jumlah_review'] = df['jumlah_review'].fillna(0)
df['jumlah_terjual'] = df['jumlah_terjual'].fillna(0)
df.info()

# @title cek hasil handle missing value
print(df.isnull().sum())
print(df.shape)
df.head()

# @title statistik deskriptif setelah handle missing value
df.describe()



"""# **Exploratory Data Analysis**

# **Global Analysis**
"""

import matplotlib.pyplot as plt

plt.figure()
plt.hist(df['harga'], bins=50, color='#3E9996', edgecolor='black')
plt.title('Distribusi Harga Produk')
plt.xlabel('Harga')
plt.ylabel('Frekuensi')
plt.show()

# @title statistika deskriptif

df[['harga', 'diskon', 'rating', 'jumlah_terjual']].describe()

# @title produk terlaris

top_produk = df.sort_values(by='jumlah_terjual', ascending=False).head(10)
top_produk[['toko', 'nama_produk', 'harga', 'jumlah_terjual']]

import matplotlib.pyplot as plt

plt.figure()
plt.scatter(df['harga'], df['jumlah_terjual'], color='#4AA9A6')

plt.title('Harga vs Penjualan')
plt.xlabel('Harga')
plt.ylabel('Jumlah Terjual')
plt.show()

# @title hubungan antara dskon dengan penjualan

plt.figure()
plt.scatter(df['diskon'], df['jumlah_terjual'], color='#4AA9A6')
plt.title('Diskon vs Penjualan')
plt.xlabel('Diskon (%)')
plt.ylabel('Jumlah Terjual')
plt.show()

# @title hubungan antara rating dengan penjualan

plt.figure()
plt.scatter(df['rating'], df['jumlah_terjual'], color='#4AA9A6')
plt.title('Rating vs Penjualan')
plt.xlabel('Rating')
plt.ylabel('Jumlah Terjual')
plt.show()

# @title korelasi antar variabel

df[['harga', 'diskon', 'rating', 'jumlah_terjual']].corr()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure()
sns.heatmap(
    df[['harga', 'diskon', 'rating', 'jumlah_terjual']].corr(),
    annot=True,
    cmap="YlGnBu"
)
plt.title('Correlation Matrix')
plt.show()

# @title pengaruh penjualan berdasarkan produk dengan review vs tanpa review

df['punya_review'] = df['jumlah_review'] > 0
df.groupby('punya_review')['jumlah_terjual'].mean()

"""# **Comparative Analysis (Watsons vs DanDan**"""

import matplotlib.pyplot as plt

plt.figure()

colors = ["#7fd8b6", "#ffe066"]  # ijo muda soft, kuning muda soft

for i, toko in enumerate(df['toko'].unique()):
    subset = df[df['toko'] == toko]
    subset['harga'].hist(
        bins=30,
        alpha=0.6,
        label=toko,
        color=colors[i % len(colors)]
    )

plt.legend()
plt.title('Distribusi Harga per Toko')
plt.show()

# @title perbandingan penjualan

df.groupby('toko')['jumlah_terjual'].describe()

# @title perbandingan rata-rata diskon yang diberikan

df.groupby('toko')['diskon'].mean()

# @title perbandingan rata-rata rating

df.groupby('toko')['rating'].mean()

plt.figure()

colors = ["#7fd8b6", "#ffe066"]

for i, toko in enumerate(df['toko'].unique()):
    subset = df[df['toko'] == toko]
    plt.scatter(
        subset['harga'],
        subset['jumlah_terjual'],
        label=toko,
        color=colors[i % len(colors)]
    )

plt.legend()
plt.title('Harga vs Penjualan per Toko')
plt.xlabel('Harga')
plt.ylabel('Jumlah Terjual')
plt.show()

plt.figure()

colors = ["#7fd8b6", "#ffe066"]

for i, toko in enumerate(df['toko'].unique()):
    subset = df[df['toko'] == toko]
    plt.scatter(
        subset['diskon'],
        subset['jumlah_terjual'],
        label=toko,
        color=colors[i % len(colors)]
    )

plt.legend()
plt.title('Diskon vs Penjualan per Toko')
plt.xlabel('Diskon')
plt.ylabel('Jumlah Terjual')
plt.show()

# @title produk terlaris per toko

top_per_toko = df.sort_values(by='jumlah_terjual', ascending=False).groupby('toko').head(5)
top_per_toko[['toko', 'nama_produk', 'jumlah_terjual']]

"""# **Add-Ons**"""

# @title hidden gems barang murah tapi laku

hidden_gems = df[
    (df['harga'] < df['harga'].median()) &
    (df['jumlah_terjual'] > df['jumlah_terjual'].quantile(0.75))
]

hidden_gems[['toko', 'nama_produk', 'harga', 'jumlah_terjual', 'rating']].head(10)

# @title outlier harga mahal banget

outlier_harga = df[df['harga'] > df['harga'].quantile(0.99)]
outlier_harga[['toko', 'nama_produk', 'harga']].sort_values(by='harga', ascending=False)
#

# @title diskon tinggi tapi nggak laku

gagal_diskon = df[
    (df['diskon'] > df['diskon'].quantile(0.75)) &
    (df['jumlah_terjual'] < df['jumlah_terjual'].median())
]

gagal_diskon[['toko', 'nama_produk', 'diskon', 'jumlah_terjual']]